server:
  port: 8091
spring:
  application:
    name: movie-info-service
  profiles:
    - active:local
---
spring:
  config:
    activate:
      on-profile:
        - local
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local

---
spring:
  config:
    activate:
      on-profile:
        - staging
  data:
    mongodb:
      host: localhost
      port: 27017
      database: staging
---
spring:
  config:
    activate:
      on-profile:
        - prod
  data:
    mongodb:
      host: localhost
      port: 27017
      database: prod

---
server:
  port: 8091
logging:
  level:
    root: info